use_frameworks!

platform :ios, '8.0'

target 'YJPresentAnimation_Example' do
  pod 'YJPresentAnimation', :path => '../'

  target 'YJPresentAnimation_Tests' do
    inherit! :search_paths

    
  end
end
